name: Create Release

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'pom.xml'

jobs:
  release:
    if: github.repository_owner == 'Mooy1'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - run: mvn package --file pom.xml

      - id: run
        run: |
          newVersion=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo New Version: $newVersion
          echo "new-version=$newVersion" >> $GITHUB_OUTPUT

          # Modified From: https://github.com/Bullrich/generate-release-changelog
          tag=$(git tag | sort -r --version-sort | head -n1)

          if [ "$tag" ]; then
            changelog=$(git log --oneline --no-decorate $tag..HEAD)
          else
            changelog=$(git log --oneline --no-decorate)
            tag="0.0.0"
          fi

          echo Old Version: $tag
          echo "old-version=$tag" >> $GITHUB_OUTPUT

          changelog="${changelog//'%'/'%25'}"
          changelog="${changelog//$'\n'/'%0A' - }"
          changelog=" - ${changelog//$'\r'/'%0D'}"
          echo "$changelog"
          echo "changelog=$changelog" >> $GITHUB_OUTPUT

      - uses: madhead/semver-utils@latest
        id: comparison
        with:
          version: ${{ steps.run.outputs.new-version }}
          compare-to: ${{ steps.run.outputs.old-version }}

      - uses: softprops/action-gh-release@v1
        if: steps.comparison.outputs.comparison-result == '>'
        with:
          tag_name: ${{ steps.run.outputs.new-version }}
          name: Release v${{ steps.run.outputs.new-version }}
          body: ${{ steps.run.outputs.changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}
